/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparkgremlin.blueprints.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroEdge extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroEdge\",\"namespace\":\"sparkgremlin.blueprints.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"src\",\"type\":\"long\"},{\"name\":\"dest\",\"type\":\"long\"},{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"props\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Property\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":[\"int\",\"boolean\",\"long\",\"string\",\"float\",\"double\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id;
  @Deprecated public long src;
  @Deprecated public long dest;
  @Deprecated public java.lang.CharSequence label;
  @Deprecated public java.util.List<sparkgremlin.blueprints.avro.Property> props;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroEdge() {}

  /**
   * All-args constructor.
   */
  public AvroEdge(java.lang.Long id, java.lang.Long src, java.lang.Long dest, java.lang.CharSequence label, java.util.List<sparkgremlin.blueprints.avro.Property> props) {
    this.id = id;
    this.src = src;
    this.dest = dest;
    this.label = label;
    this.props = props;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return src;
    case 2: return dest;
    case 3: return label;
    case 4: return props;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: src = (java.lang.Long)value$; break;
    case 2: dest = (java.lang.Long)value$; break;
    case 3: label = (java.lang.CharSequence)value$; break;
    case 4: props = (java.util.List<sparkgremlin.blueprints.avro.Property>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'src' field.
   */
  public java.lang.Long getSrc() {
    return src;
  }

  /**
   * Sets the value of the 'src' field.
   * @param value the value to set.
   */
  public void setSrc(java.lang.Long value) {
    this.src = value;
  }

  /**
   * Gets the value of the 'dest' field.
   */
  public java.lang.Long getDest() {
    return dest;
  }

  /**
   * Sets the value of the 'dest' field.
   * @param value the value to set.
   */
  public void setDest(java.lang.Long value) {
    this.dest = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /**
   * Gets the value of the 'props' field.
   */
  public java.util.List<sparkgremlin.blueprints.avro.Property> getProps() {
    return props;
  }

  /**
   * Sets the value of the 'props' field.
   * @param value the value to set.
   */
  public void setProps(java.util.List<sparkgremlin.blueprints.avro.Property> value) {
    this.props = value;
  }

  /** Creates a new AvroEdge RecordBuilder */
  public static sparkgremlin.blueprints.avro.AvroEdge.Builder newBuilder() {
    return new sparkgremlin.blueprints.avro.AvroEdge.Builder();
  }
  
  /** Creates a new AvroEdge RecordBuilder by copying an existing Builder */
  public static sparkgremlin.blueprints.avro.AvroEdge.Builder newBuilder(sparkgremlin.blueprints.avro.AvroEdge.Builder other) {
    return new sparkgremlin.blueprints.avro.AvroEdge.Builder(other);
  }
  
  /** Creates a new AvroEdge RecordBuilder by copying an existing AvroEdge instance */
  public static sparkgremlin.blueprints.avro.AvroEdge.Builder newBuilder(sparkgremlin.blueprints.avro.AvroEdge other) {
    return new sparkgremlin.blueprints.avro.AvroEdge.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroEdge instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroEdge>
    implements org.apache.avro.data.RecordBuilder<AvroEdge> {

    private long id;
    private long src;
    private long dest;
    private java.lang.CharSequence label;
    private java.util.List<sparkgremlin.blueprints.avro.Property> props;

    /** Creates a new Builder */
    private Builder() {
      super(sparkgremlin.blueprints.avro.AvroEdge.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparkgremlin.blueprints.avro.AvroEdge.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.src)) {
        this.src = data().deepCopy(fields()[1].schema(), other.src);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dest)) {
        this.dest = data().deepCopy(fields()[2].schema(), other.dest);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.label)) {
        this.label = data().deepCopy(fields()[3].schema(), other.label);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.props)) {
        this.props = data().deepCopy(fields()[4].schema(), other.props);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroEdge instance */
    private Builder(sparkgremlin.blueprints.avro.AvroEdge other) {
            super(sparkgremlin.blueprints.avro.AvroEdge.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.src)) {
        this.src = data().deepCopy(fields()[1].schema(), other.src);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dest)) {
        this.dest = data().deepCopy(fields()[2].schema(), other.dest);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.label)) {
        this.label = data().deepCopy(fields()[3].schema(), other.label);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.props)) {
        this.props = data().deepCopy(fields()[4].schema(), other.props);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'src' field */
    public java.lang.Long getSrc() {
      return src;
    }
    
    /** Sets the value of the 'src' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder setSrc(long value) {
      validate(fields()[1], value);
      this.src = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'src' field has been set */
    public boolean hasSrc() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'src' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder clearSrc() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'dest' field */
    public java.lang.Long getDest() {
      return dest;
    }
    
    /** Sets the value of the 'dest' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder setDest(long value) {
      validate(fields()[2], value);
      this.dest = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'dest' field has been set */
    public boolean hasDest() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'dest' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder clearDest() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.label = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'label' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder clearLabel() {
      label = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'props' field */
    public java.util.List<sparkgremlin.blueprints.avro.Property> getProps() {
      return props;
    }
    
    /** Sets the value of the 'props' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder setProps(java.util.List<sparkgremlin.blueprints.avro.Property> value) {
      validate(fields()[4], value);
      this.props = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'props' field has been set */
    public boolean hasProps() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'props' field */
    public sparkgremlin.blueprints.avro.AvroEdge.Builder clearProps() {
      props = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public AvroEdge build() {
      try {
        AvroEdge record = new AvroEdge();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.src = fieldSetFlags()[1] ? this.src : (java.lang.Long) defaultValue(fields()[1]);
        record.dest = fieldSetFlags()[2] ? this.dest : (java.lang.Long) defaultValue(fields()[2]);
        record.label = fieldSetFlags()[3] ? this.label : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.props = fieldSetFlags()[4] ? this.props : (java.util.List<sparkgremlin.blueprints.avro.Property>) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
