/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparkgraph.blueprints.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroEdge extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroEdge\",\"namespace\":\"sparkgraph.blueprints.avro\",\"fields\":[{\"name\":\"src\",\"type\":\"long\"},{\"name\":\"dest\",\"type\":\"long\"},{\"name\":\"label\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long src;
  @Deprecated public long dest;
  @Deprecated public java.lang.CharSequence label;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroEdge() {}

  /**
   * All-args constructor.
   */
  public AvroEdge(java.lang.Long src, java.lang.Long dest, java.lang.CharSequence label) {
    this.src = src;
    this.dest = dest;
    this.label = label;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return src;
    case 1: return dest;
    case 2: return label;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: src = (java.lang.Long)value$; break;
    case 1: dest = (java.lang.Long)value$; break;
    case 2: label = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'src' field.
   */
  public java.lang.Long getSrc() {
    return src;
  }

  /**
   * Sets the value of the 'src' field.
   * @param value the value to set.
   */
  public void setSrc(java.lang.Long value) {
    this.src = value;
  }

  /**
   * Gets the value of the 'dest' field.
   */
  public java.lang.Long getDest() {
    return dest;
  }

  /**
   * Sets the value of the 'dest' field.
   * @param value the value to set.
   */
  public void setDest(java.lang.Long value) {
    this.dest = value;
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
  }

  /** Creates a new AvroEdge RecordBuilder */
  public static sparkgraph.blueprints.avro.AvroEdge.Builder newBuilder() {
    return new sparkgraph.blueprints.avro.AvroEdge.Builder();
  }
  
  /** Creates a new AvroEdge RecordBuilder by copying an existing Builder */
  public static sparkgraph.blueprints.avro.AvroEdge.Builder newBuilder(sparkgraph.blueprints.avro.AvroEdge.Builder other) {
    return new sparkgraph.blueprints.avro.AvroEdge.Builder(other);
  }
  
  /** Creates a new AvroEdge RecordBuilder by copying an existing AvroEdge instance */
  public static sparkgraph.blueprints.avro.AvroEdge.Builder newBuilder(sparkgraph.blueprints.avro.AvroEdge other) {
    return new sparkgraph.blueprints.avro.AvroEdge.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroEdge instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroEdge>
    implements org.apache.avro.data.RecordBuilder<AvroEdge> {

    private long src;
    private long dest;
    private java.lang.CharSequence label;

    /** Creates a new Builder */
    private Builder() {
      super(sparkgraph.blueprints.avro.AvroEdge.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparkgraph.blueprints.avro.AvroEdge.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.src)) {
        this.src = data().deepCopy(fields()[0].schema(), other.src);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dest)) {
        this.dest = data().deepCopy(fields()[1].schema(), other.dest);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroEdge instance */
    private Builder(sparkgraph.blueprints.avro.AvroEdge other) {
            super(sparkgraph.blueprints.avro.AvroEdge.SCHEMA$);
      if (isValidValue(fields()[0], other.src)) {
        this.src = data().deepCopy(fields()[0].schema(), other.src);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dest)) {
        this.dest = data().deepCopy(fields()[1].schema(), other.dest);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'src' field */
    public java.lang.Long getSrc() {
      return src;
    }
    
    /** Sets the value of the 'src' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder setSrc(long value) {
      validate(fields()[0], value);
      this.src = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'src' field has been set */
    public boolean hasSrc() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'src' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder clearSrc() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'dest' field */
    public java.lang.Long getDest() {
      return dest;
    }
    
    /** Sets the value of the 'dest' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder setDest(long value) {
      validate(fields()[1], value);
      this.dest = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'dest' field has been set */
    public boolean hasDest() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'dest' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder clearDest() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.label = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'label' field */
    public sparkgraph.blueprints.avro.AvroEdge.Builder clearLabel() {
      label = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public AvroEdge build() {
      try {
        AvroEdge record = new AvroEdge();
        record.src = fieldSetFlags()[0] ? this.src : (java.lang.Long) defaultValue(fields()[0]);
        record.dest = fieldSetFlags()[1] ? this.dest : (java.lang.Long) defaultValue(fields()[1]);
        record.label = fieldSetFlags()[2] ? this.label : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
