/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparkgraph.blueprints.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroVertex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroVertex\",\"namespace\":\"sparkgraph.blueprints.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"props\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Property\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":[\"int\",\"boolean\",\"long\",\"string\",\"float\",\"double\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id;
  @Deprecated public java.util.List<sparkgraph.blueprints.avro.Property> props;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroVertex() {}

  /**
   * All-args constructor.
   */
  public AvroVertex(java.lang.Long id, java.util.List<sparkgraph.blueprints.avro.Property> props) {
    this.id = id;
    this.props = props;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return props;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: props = (java.util.List<sparkgraph.blueprints.avro.Property>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'props' field.
   */
  public java.util.List<sparkgraph.blueprints.avro.Property> getProps() {
    return props;
  }

  /**
   * Sets the value of the 'props' field.
   * @param value the value to set.
   */
  public void setProps(java.util.List<sparkgraph.blueprints.avro.Property> value) {
    this.props = value;
  }

  /** Creates a new AvroVertex RecordBuilder */
  public static sparkgraph.blueprints.avro.AvroVertex.Builder newBuilder() {
    return new sparkgraph.blueprints.avro.AvroVertex.Builder();
  }
  
  /** Creates a new AvroVertex RecordBuilder by copying an existing Builder */
  public static sparkgraph.blueprints.avro.AvroVertex.Builder newBuilder(sparkgraph.blueprints.avro.AvroVertex.Builder other) {
    return new sparkgraph.blueprints.avro.AvroVertex.Builder(other);
  }
  
  /** Creates a new AvroVertex RecordBuilder by copying an existing AvroVertex instance */
  public static sparkgraph.blueprints.avro.AvroVertex.Builder newBuilder(sparkgraph.blueprints.avro.AvroVertex other) {
    return new sparkgraph.blueprints.avro.AvroVertex.Builder(other);
  }
  
  /**
   * RecordBuilder for AvroVertex instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroVertex>
    implements org.apache.avro.data.RecordBuilder<AvroVertex> {

    private long id;
    private java.util.List<sparkgraph.blueprints.avro.Property> props;

    /** Creates a new Builder */
    private Builder() {
      super(sparkgraph.blueprints.avro.AvroVertex.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(sparkgraph.blueprints.avro.AvroVertex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.props)) {
        this.props = data().deepCopy(fields()[1].schema(), other.props);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroVertex instance */
    private Builder(sparkgraph.blueprints.avro.AvroVertex other) {
            super(sparkgraph.blueprints.avro.AvroVertex.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.props)) {
        this.props = data().deepCopy(fields()[1].schema(), other.props);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public sparkgraph.blueprints.avro.AvroVertex.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public sparkgraph.blueprints.avro.AvroVertex.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'props' field */
    public java.util.List<sparkgraph.blueprints.avro.Property> getProps() {
      return props;
    }
    
    /** Sets the value of the 'props' field */
    public sparkgraph.blueprints.avro.AvroVertex.Builder setProps(java.util.List<sparkgraph.blueprints.avro.Property> value) {
      validate(fields()[1], value);
      this.props = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'props' field has been set */
    public boolean hasProps() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'props' field */
    public sparkgraph.blueprints.avro.AvroVertex.Builder clearProps() {
      props = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroVertex build() {
      try {
        AvroVertex record = new AvroVertex();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.props = fieldSetFlags()[1] ? this.props : (java.util.List<sparkgraph.blueprints.avro.Property>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
