/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparkgraph.blueprints.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Blueprints {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Blueprints\",\"namespace\":\"sparkgraph.blueprints.avro\",\"types\":[{\"type\":\"enum\",\"name\":\"ElementType\",\"symbols\":[\"VERTEX\",\"EDGE\"]},{\"type\":\"record\",\"name\":\"AvroProperty\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"value\",\"type\":[\"int\",\"boolean\",\"long\",\"string\",\"float\",\"double\"]}]},{\"type\":\"record\",\"name\":\"AvroEdge\",\"fields\":[{\"name\":\"src\",\"type\":\"long\"},{\"name\":\"dest\",\"type\":\"long\"},{\"name\":\"label\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"AvroElement\",\"fields\":[{\"name\":\"type\",\"type\":\"ElementType\"},{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"props\",\"type\":{\"type\":\"array\",\"items\":\"AvroProperty\"}},{\"name\":\"edge\",\"type\":[\"null\",\"AvroEdge\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Blueprints {
    public static final org.apache.avro.Protocol PROTOCOL = sparkgraph.blueprints.avro.Blueprints.PROTOCOL;
  }
}