/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package sparkgraph.blueprints.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ElementType { 
  VERTEX, EDGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ElementType\",\"namespace\":\"sparkgraph.blueprints.avro\",\"symbols\":[\"VERTEX\",\"EDGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
